#!/usr/bin/env npx tsx
/**
 * Converts WASM binary files to base64-encoded TypeScript modules.
 *
 * This script reads compiled .wasm files from wasm-build/ and generates
 * TypeScript files with the WASM binary inlined as a base64 string.
 *
 * This enables zero-config usage - users don't need to configure their
 * bundler to handle .wasm files.
 */

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const WASM_BUILD_DIR = join(__dirname, '..', 'wasm-build');
const ALGORITHMS_DIR = join(__dirname, '..', 'src', 'algorithms');

const ALGORITHMS = ['zstd', 'brotli', 'zlib', 'bz2', 'lz4', 'xz'] as const;

interface WasmStats {
  algorithm: string;
  wasmSize: number;
  base64Size: number;
}

function generateWasmModule(algorithm: string): WasmStats | null {
  const wasmPath = join(WASM_BUILD_DIR, `${algorithm}.wasm`);
  const outputPath = join(ALGORITHMS_DIR, algorithm, 'wasm.generated.ts');

  if (!existsSync(wasmPath)) {
    console.log(`  Skipping ${algorithm}: ${algorithm}.wasm not found`);
    return null;
  }

  // Read WASM binary
  const wasmBinary = readFileSync(wasmPath);
  const base64 = wasmBinary.toString('base64');

  // Generate TypeScript module
  const tsContent = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/inline-wasm.ts
// Source: ${algorithm}.wasm (${wasmBinary.length} bytes)

/**
 * Base64-encoded WASM binary for the ${algorithm} algorithm.
 * @internal
 */
export const WASM_BASE64 = "${base64}";

/**
 * Size of the original WASM binary in bytes.
 * @internal
 */
export const WASM_SIZE = ${wasmBinary.length};
`;

  writeFileSync(outputPath, tsContent, 'utf-8');

  console.log(
    `  ✓ ${algorithm}: ${wasmBinary.length} bytes → ${base64.length} bytes (base64)`
  );

  return {
    algorithm,
    wasmSize: wasmBinary.length,
    base64Size: base64.length,
  };
}

function main(): void {
  console.log('Converting WASM binaries to TypeScript modules...\n');

  if (!existsSync(WASM_BUILD_DIR)) {
    console.error(`Error: Build directory not found: ${WASM_BUILD_DIR}`);
    console.error('Run build-wasm.sh first to compile WASM modules.');
    process.exit(1);
  }

  const stats: WasmStats[] = [];

  for (const algorithm of ALGORITHMS) {
    const result = generateWasmModule(algorithm);
    if (result) {
      stats.push(result);
    }
  }

  if (stats.length === 0) {
    console.log('\nNo WASM files found to process.');
    return;
  }

  // Print summary
  console.log('\n─────────────────────────────────────────────────');
  console.log('Summary:');
  console.log('─────────────────────────────────────────────────');

  const totalWasm = stats.reduce((sum, s) => sum + s.wasmSize, 0);
  const totalBase64 = stats.reduce((sum, s) => sum + s.base64Size, 0);

  console.log(`  Algorithms: ${stats.length}`);
  console.log(`  Total WASM: ${(totalWasm / 1024).toFixed(1)} KB`);
  console.log(`  Total Base64: ${(totalBase64 / 1024).toFixed(1)} KB`);
  console.log(
    `  Overhead: ${(((totalBase64 - totalWasm) / totalWasm) * 100).toFixed(1)}%`
  );
  console.log('');
}

main();
