/**
 * Auto-generated declaration for Emscripten WASM module.
 * The actual module is generated by Emscripten during build.
 */
import type { EmscriptenModuleFactory } from '../../core/loader.js';

declare const Module: EmscriptenModuleFactory;
export default Module;
