// Code generated by tools/gen-go-cgo.py from third_party/manifest.json. DO NOT EDIT.

package compressutils

// Manifest-derived cgo flags: -I dirs for the vendored codec headers +
// our own headers, and the per-algorithm INCLUDE_<ALGO> switches the
// registry compiles on. LZMA_API_STATIC is global (only <lzma.h> reads
// it). CPPFLAGS apply to both the C and C++ (snappy) shims. Runtime link
// flags live in the hand-written cgo.go preamble.

// #cgo CPPFLAGS: -I${SRCDIR}/../../include
// #cgo CPPFLAGS: -I${SRCDIR}/../../src
// #cgo CPPFLAGS: -I${SRCDIR}/../../third_party/brotli/c/include
// #cgo CPPFLAGS: -I${SRCDIR}/../../third_party/bz2
// #cgo CPPFLAGS: -I${SRCDIR}/../../third_party/lz4/lib
// #cgo CPPFLAGS: -I${SRCDIR}/../../third_party/snappy
// #cgo CPPFLAGS: -I${SRCDIR}/../../third_party/xz/src/liblzma/api
// #cgo CPPFLAGS: -I${SRCDIR}/../../third_party/xz/src/liblzma/common
// #cgo CPPFLAGS: -I${SRCDIR}/../../third_party/xz/src/liblzma/check
// #cgo CPPFLAGS: -I${SRCDIR}/../../third_party/xz/src/liblzma/lz
// #cgo CPPFLAGS: -I${SRCDIR}/../../third_party/xz/src/liblzma/rangecoder
// #cgo CPPFLAGS: -I${SRCDIR}/../../third_party/xz/src/liblzma/lzma
// #cgo CPPFLAGS: -I${SRCDIR}/../../third_party/xz/src/liblzma/delta
// #cgo CPPFLAGS: -I${SRCDIR}/../../third_party/xz/src/liblzma/simple
// #cgo CPPFLAGS: -I${SRCDIR}/../../third_party/xz/src/common
// #cgo CPPFLAGS: -I${SRCDIR}/../../third_party/zlib
// #cgo CPPFLAGS: -I${SRCDIR}/../../third_party/zstd/lib
// #cgo CPPFLAGS: -DINCLUDE_ZSTD -DINCLUDE_BROTLI -DINCLUDE_ZLIB -DINCLUDE_GZIP -DINCLUDE_BZ2 -DINCLUDE_LZ4 -DINCLUDE_XZ -DINCLUDE_SNAPPY -DLZMA_API_STATIC
import "C"
