/* Code generated by tools/gen-go-cgo.py from third_party/manifest.json. DO NOT EDIT. */
#define XXH_NAMESPACE ZSTD_
#define ZSTD_LEGACY_SUPPORT 0
#define ZSTD_DISABLE_ASM 1

#include "../../third_party/zstd/lib/compress/zstd_fast.c"
