/**
 * ZSTD WASM Module Loader
 *
 * Handles loading and initialization of the ZSTD WebAssembly module.
 * The module is lazily loaded on first use and cached for subsequent calls.
 */

import {
  getModule,
  isModuleLoaded,
  preloadModule,
  type WasmModule,
} from '../../core/index.js';

// This will be generated by the build process
let wasmBase64Cache: string | null = null;

// Dynamic import for the generated WASM module
async function loadWasmBase64(): Promise<string> {
  if (wasmBase64Cache !== null) {
    return wasmBase64Cache;
  }

  try {
    // Try to import the generated module
    const module = await import('./wasm.generated.js') as { WASM_BASE64: string };
    wasmBase64Cache = module.WASM_BASE64;
    return wasmBase64Cache;
  } catch {
    throw new Error(
      'ZSTD WASM module not found. Run the build script first: npm run build:wasm'
    );
  }
}

/**
 * Gets the initialized ZSTD WASM module.
 *
 * This function lazily loads and initializes the WASM module on first call.
 * Subsequent calls return the cached module instance.
 *
 * @returns Promise resolving to the WASM module
 * @throws CompressError if module initialization fails
 */
export async function getZstdModule(): Promise<WasmModule> {
  const wasmBase64 = await loadWasmBase64();
  return getModule('zstd', wasmBase64);
}

/**
 * Checks if the ZSTD WASM module is already loaded.
 *
 * @returns True if the module is loaded and ready
 */
export function isZstdModuleLoaded(): boolean {
  return isModuleLoaded('zstd');
}

/**
 * Preloads the ZSTD WASM module.
 *
 * Call this early in your application to avoid first-call latency.
 * This is optional - the module will be automatically loaded on first use.
 *
 * @example
 * ```typescript
 * // Preload during app initialization
 * import { preload } from 'compress-utils/zstd';
 *
 * await preload();
 *
 * // Later, compression is instant (no loading delay)
 * const compressed = await compress(data);
 * ```
 */
export async function preload(): Promise<void> {
  const wasmBase64 = await loadWasmBase64();
  await preloadModule('zstd', wasmBase64);
}
