#!/usr/bin/env python3
"""
gen-go-cgo.py — generate the cgo shim translation units for the Go binding.

Why this exists: cgo only compiles C/C++ that physically sits in the package
directory (bindings/go), under one global set of flags. Our codec sources live
in third_party/ (shared across every binding) and need *conflicting* per-codec
macros — zstd compiles xxhash.c with XXH_NAMESPACE=ZSTD_, lz4 with =LZ4_. So we
emit thin shim .c/.cc files into bindings/go that #define a codec's macros and
#include its vendored sources by relative path: this relocates the compile into
the package (satisfying cgo) and scopes macros per translation unit.

Shim shapes:
  * per-codec "unity" (default): one shim #includes all of a codec's sources.
    Fewest files. Needs the codec to tolerate being one translation unit.
  * 1:1 (UNITY[codec] = False): one shim per source. Always safe — mirrors how
    CMake compiles each source as its own TU. The fallback for codecs whose
    sources collide when unified.

Also emits cgo_generated.go: the -I include dirs and -DINCLUDE_<ALGO> flags,
derived from third_party/manifest.json (via CPPFLAGS, which apply to both the C
and C++ shims).

This runs at *maintenance* time — after adding/bumping a codec, run it and
commit the output. CI runs `--check` (regenerate in memory, diff the committed
tree) to catch drift. It NEVER runs on `go get`: the generated files are
committed and ship in the module; the consumer only needs a C compiler.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MANIFEST = REPO / "third_party" / "manifest.json"
GO_DIR = REPO / "bindings" / "go"
GEN_PREFIX = "cu_gen_"  # every generated C shim starts with this
# Every generated C shim stem ends with this. Go applies build constraints from
# filename suffixes: a file ending _<GOOS>.c / _<GOARCH>.c (e.g. _arm, _riscv,
# _sparc — all recognized GOARCH tokens that appear in xz's simple/ sources) is
# silently excluded on other targets. A constant trailing token neutralizes that.
GEN_SUFFIX = "_cgen"
GEN_GO = "cgo_generated.go"

# All algorithms the binding exposes. gzip is not a manifest codec — it is zlib
# in a different wire wrapper, so it contributes a vtable + INCLUDE_GZIP but no
# codec sources of its own (it links zlib's).
ALGOS = ["zstd", "brotli", "zlib", "gzip", "bz2", "lz4", "xz", "snappy"]

# Our own translation units (not upstream): the ABI dispatcher, the registry,
# and one vtable per algorithm. Compiled with the global INCLUDE_* defines; no
# per-codec private macros needed.
CORE_SOURCES = ["compress_utils.c", "registry.c"]

# Per-codec unity toggle. Default False: emit one shim per source (1:1), which
# mirrors how CMake compiles each source as its own translation unit and is
# always safe. Unity (all of a codec's sources in one TU) would mean fewer
# files, but the upstreams are written for separate TUs — their internal
# headers reuse macros/typedefs and lack include guards, so a single TU breaks
# (zlib's gzguts.h/inftrees.h, xz's many internal headers, etc.). Left as an
# opt-in per codec in case one is ever verified unity-safe; none are today.
UNITY = {c: False for c in ALGOS}


def load_manifest() -> dict:
    import json
    return json.loads(MANIFEST.read_text())["codecs"]


def define_line(d: str) -> str:
    """A manifest define -> a #define line. 'K=V' -> '#define K V' (V keeps any
    quotes it already carries, e.g. PACKAGE_NAME="XZ Utils"); bare 'K' -> '=1'."""
    if "=" in d:
        k, v = d.split("=", 1)
        return f"#define {k} {v}"
    return f"#define {d} 1"


def banner() -> str:
    return ("/* Code generated by tools/gen-go-cgo.py from "
            "third_party/manifest.json. DO NOT EDIT. */\n")


def codec_shims(codec: str, entry: dict) -> dict[str, str]:
    """Return {filename: content} for one codec's shim(s)."""
    ext = ".cc" if entry["cxx"] else ".c"
    defines = "".join(define_line(d) + "\n" for d in entry["defines"])
    out: dict[str, str] = {}

    if UNITY.get(codec, True):
        includes = "".join(
            f'#include "../../third_party/{codec}/{s}"\n' for s in entry["sources"])
        out[f"{GEN_PREFIX}codec_{codec}{GEN_SUFFIX}{ext}"] = (
            banner()
            + f"/* {codec}: unity translation unit ({len(entry['sources'])} "
              f"sources). Per-codec macros scoped to this TU. */\n\n"
            + defines + "\n" + includes)
    else:
        for s in entry["sources"]:
            flat = s.replace("/", "_").rsplit(".", 1)[0]
            out[f"{GEN_PREFIX}codec_{codec}__{flat}{GEN_SUFFIX}{ext}"] = (
                banner() + defines + "\n"
                + f'#include "../../third_party/{codec}/{s}"\n')
    return out


def core_and_vtable_shims() -> dict[str, str]:
    """Shims for our own sources: ABI core + one vtable per algorithm. These
    carry no private macros (the global INCLUDE_* / LZMA_API_STATIC cover
    them), so each is a plain one-line include."""
    out: dict[str, str] = {}
    for name in CORE_SOURCES:
        stem = name.rsplit(".", 1)[0]
        out[f"{GEN_PREFIX}core_{stem}{GEN_SUFFIX}.c"] = (
            banner() + f'#include "../../src/{name}"\n')
    for algo in ALGOS:
        out[f"{GEN_PREFIX}vtbl_{algo}{GEN_SUFFIX}.c"] = (
            banner() + f'#include "../../src/algorithms/{algo}/{algo}.c"\n')
    return out


def cgo_generated_go(codecs: dict) -> dict[str, str]:
    """The generated Go file carrying manifest-derived cgo flags. Uses CPPFLAGS
    (preprocessor flags apply to both the C and C++ shims). Include dirs and the
    INCLUDE_<ALGO> set track the manifest; runtime/link flags (C++ stdlib, libm)
    live in the hand-written cgo.go so this stays purely manifest-derived."""
    incs = ["${SRCDIR}/../../include", "${SRCDIR}/../../src"]
    for codec, entry in sorted(codecs.items()):
        for d in entry["include_dirs"]:
            sub = f"/{d}" if d not in (".", "") else ""
            incs.append(f"${{SRCDIR}}/../../third_party/{codec}{sub}")
    inc_lines = "".join(f"// #cgo CPPFLAGS: -I{p}\n" for p in incs)
    defs = " ".join(f"-DINCLUDE_{a.upper()}" for a in ALGOS)
    # NOTE: the comment group immediately above `import "C"` is the cgo preamble,
    # and cgo treats each line's content as C source (the `//` is stripped) — so
    # it must contain ONLY `#cgo` directives. Explanatory prose goes in a
    # separate comment group detached by a blank line, or cgo feeds it to the C
    # compiler ("unknown type name ...").
    body = (
        "// Code generated by tools/gen-go-cgo.py from third_party/manifest.json. "
        "DO NOT EDIT.\n\n"
        "package compressutils\n\n"
        "// Manifest-derived cgo flags: -I dirs for the vendored codec headers +\n"
        "// our own headers, and the per-algorithm INCLUDE_<ALGO> switches the\n"
        "// registry compiles on. LZMA_API_STATIC is global (only <lzma.h> reads\n"
        "// it). CPPFLAGS apply to both the C and C++ (snappy) shims. Runtime link\n"
        "// flags live in the hand-written cgo.go preamble.\n"
        "\n"
        + inc_lines
        + f"// #cgo CPPFLAGS: {defs} -DLZMA_API_STATIC\n"
        "import \"C\"\n")
    return {GEN_GO: body}


def generate(codecs: dict) -> dict[str, str]:
    files: dict[str, str] = {}
    for codec, entry in codecs.items():
        files.update(codec_shims(codec, entry))
    files.update(core_and_vtable_shims())
    files.update(cgo_generated_go(codecs))
    return files


def existing_generated() -> set[str]:
    found = {p.name for p in GO_DIR.glob(f"{GEN_PREFIX}*") if p.suffix in (".c", ".cc")}
    if (GO_DIR / GEN_GO).exists():
        found.add(GEN_GO)
    return found


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify committed shims match the manifest; nonzero on drift")
    args = ap.parse_args()

    codecs = load_manifest()
    want = generate(codecs)

    if args.check:
        have = existing_generated()
        drift = False
        for name in sorted(set(want) | have):
            path = GO_DIR / name
            if name not in have:
                print(f"MISSING  {name}"); drift = True
            elif name not in want:
                print(f"STALE    {name} (no longer generated)"); drift = True
            elif path.read_text() != want[name]:
                print(f"CHANGED  {name}"); drift = True
        if drift:
            print("\nGo cgo shims are out of sync — run tools/gen-go-cgo.py "
                  "and commit the result.")
            return 1
        print(f"ok  {len(want)} generated Go cgo files match the manifest")
        return 0

    # Write mode: refresh the generated set, removing any now-stale files.
    for name in existing_generated() - set(want):
        (GO_DIR / name).unlink()
        print(f"removed stale {name}")
    for name, content in sorted(want.items()):
        (GO_DIR / name).write_text(content)
    n_c = sum(1 for n in want if n != GEN_GO)
    print(f"wrote {n_c} shim files + {GEN_GO} to bindings/go/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
