/**
 * Auto-generated WASM module type declaration.
 * The actual module is generated by scripts/inline-wasm.ts during build.
 */

/** Base64-encoded WASM binary */
export declare const WASM_BASE64: string;

/** Size of the original WASM binary in bytes */
export declare const WASM_SIZE: number;
