name: Build and Package Language Bindings

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: true

    - name: Configure CMake for All Language Bindings & All Compressors
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build All Languages
      run: cmake --build build --config Release -j 4

    - name: Install Bindings
      run: cmake --install build

    - name: Test All Bindings & Compressors
      run: |
        cd build
        ctest --output-on-failure -C Release

    - name: Zip C Bindings
      run: |
        cd dist
        if [ "${{ runner.os }}" == "Windows" ]; then
          Compress-Archive -Path c -DestinationPath c-bindings-${{ matrix.os }}.zip
        else
          zip -r c-bindings-${{ matrix.os }}.zip c
        fi
      shell: bash

    - name: Zip C++ Bindings
      run: |
        cd dist
        if [ "${{ runner.os }}" == "Windows" ]; then
          Compress-Archive -Path cpp -DestinationPath cpp-bindings-${{ matrix.os }}.zip
        else
          zip -r cpp-bindings-${{ matrix.os }}.zip cpp
        fi
      shell: bash

    - name: Upload C Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: c-bindings-${{ matrix.os }}
        path: dist/c-bindings-${{ matrix.os }}.zip
        retention-days: 1  # These artifacts are only used for the `combine` step

    - name: Upload C++ Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cpp-bindings-${{ matrix.os }}
        path: dist/cpp-bindings-${{ matrix.os }}.zip
        retention-days: 1  # These artifacts are only used for the `combine` step

  combine:
    needs: build
    runs-on: ubuntu-latest

    steps:

   ##### C Artifacts #####

    - name: Create C Artifact Directories
      # run: mkdir -p compression-utils-c/macos compression-utils-c/linux compression-utils-c/windows
      run: mkdir -p compression-utils-c/macos compression-utils-c/linux

    - name: Download C Artifacts from macOS
      uses: actions/download-artifact@v4
      with:
        name: c-bindings-macos-latest
        path: compression-utils-c/macos

    - name: Download C Artifacts from Ubuntu
      uses: actions/download-artifact@v4
      with:
        name: c-bindings-ubuntu-latest
        path: compression-utils-c/linux

    - name: Download C Artifacts from Windows
      uses: actions/download-artifact@v4
      with:
        name: c-bindings-windows-latest
        path: compression-utils-c/windows

    - name: Unzip C Artifacts from macOS
      run: |
        unzip -o compression-utils-c/macos/c-bindings-macos-latest.zip -d compression-utils-c/macos
        mv compression-utils-c/macos/c/* compression-utils-c/macos/
        rm -r compression-utils-c/macos/c
        rm compression-utils-c/macos/c-bindings-macos-latest.zip

    - name: Unzip C Artifacts from Ubuntu
      run: |
        unzip -o compression-utils-c/linux/c-bindings-ubuntu-latest.zip -d compression-utils-c/linux
        mv compression-utils-c/linux/c/* compression-utils-c/linux/
        rm -r compression-utils-c/linux/c
        rm compression-utils-c/linux/c-bindings-ubuntu-latest.zip
      
    - name: Unzip C Artifacts from Windows
      run: |
        unzip -o compression-utils-c/windows/c-bindings-windows-latest.zip -d compression-utils-c/windows
        mv compression-utils-c/windows/c/* compression-utils-c/windows/
        rm -r compression-utils-c/windows/c
        rm compression-utils-c/windows/c-bindings-windows-latest.zip

    ##### C++ Artifacts #####

    - name: Create C++ Artifact Directories
      run: mkdir -p compression-utils-cpp/macos compression-utils-cpp/linux compression-utils-cpp/windows

    - name: Download C++ Artifacts from macOS
      uses: actions/download-artifact@v4
      with:
        name: cpp-bindings-macos-latest
        path: compression-utils-cpp/macos

    - name: Download C++ Artifacts from Ubuntu
      uses: actions/download-artifact@v4
      with:
        name: cpp-bindings-ubuntu-latest
        path: compression-utils-cpp/linux

    - name: Download C++ Artifacts from Windows
      uses: actions/download-artifact@v4
      with:
        name: cpp-bindings-windows-latest
        path: compression-utils-cpp/windows

    - name: Unzip C++ Artifacts from macOS
      run: |
        unzip -o compression-utils-cpp/macos/cpp-bindings-macos-latest.zip -d compression-utils-cpp/macos
        mv compression-utils-cpp/macos/cpp/* compression-utils-cpp/macos/
        rm -r compression-utils-cpp/macos/cpp
        rm compression-utils-cpp/macos/cpp-bindings-macos-latest.zip

    - name: Unzip C++ Artifacts from Ubuntu
      run: |
        unzip -o compression-utils-cpp/linux/cpp-bindings-ubuntu-latest.zip -d compression-utils-cpp/linux
        mv compression-utils-cpp/linux/cpp/* compression-utils-cpp/linux/
        rm -r compression-utils-cpp/linux/cpp
        rm compression-utils-cpp/linux/cpp-bindings-ubuntu-latest.zip
      
    - name: Unzip C++ Artifacts from Windows
      run: |
        unzip -o compression-utils-cpp/windows/cpp-bindings-windows-latest.zip -d compression-utils-cpp/windows
        mv compression-utils-cpp/windows/cpp/* compression-utils-cpp/windows/
        rm -r compression-utils-cpp/windows/cpp
        rm compression-utils-cpp/windows/cpp-bindings-windows-latest.zip

    ##### Merge All Artifacts #####

    - name: Zip All C Artifacts Together
      run: zip -r compression-utils-c.zip compression-utils-c

    - name: Zip All C++ Artifacts Together
      run: zip -r compression-utils-cpp.zip compression-utils-cpp

    ##### Upload Artifacts #####

    - name: Upload Unified C Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compression-utils-c
        path: compression-utils-c.zip

    - name: Upload Unified C++ Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compression-utils-cpp
        path: compression-utils-cpp.zip
