name: Build and Package Language Bindings

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: true

    - name: Configure CMake for All Language Bindings & All Compressors
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build All Languages
      run: cmake --build build --config Release -j 4

    - name: Install Bindings
      run: cmake --install build

    - name: Test All Bindings & Compressors
      run: |
        cd build
        ctest --output-on-failure

    - name: Zip C Bindings
      run: |
        cd dist
        zip -r c-bindings-${{ matrix.os }}.zip c

    - name: Zip C++ Bindings
      run: |
        cd dist
        zip -r cpp-bindings-${{ matrix.os }}.zip cpp

    - name: Upload C Bindings
      uses: actions/upload-artifact@v3
      with:
        name: c-bindings-${{ matrix.os }}
        path: dist/c-bindings-${{ matrix.os }}.zip

    - name: Upload C++ Bindings
      uses: actions/upload-artifact@v3
      with:
        name: cpp-bindings-${{ matrix.os }}
        path: dist/cpp-bindings-${{ matrix.os }}.zip

  combine:
    needs: build
    runs-on: ubuntu-latest

    steps:

   ##### C Bindings #####

    - name: Download and Unzip C Bindings from All OSes
      # run: mkdir -p dist/c/macos dist/c/linux dist/c/windows
      run: mkdir -p dist/c/macos dist/c/linux

    - name: Download C Bindings from macOS
      uses: actions/download-artifact@v3
      with:
        name: c-bindings-macos-latest
        path: dist/c/macos

    - name: Download C Bindings from Ubuntu
      uses: actions/download-artifact@v3
      with:
        name: c-bindings-ubuntu-latest
        path: dist/c/linux

    # Skipping Windows for now
    # - name: Download C Bindings from Windows
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: c-bindings-windows-latest
    #     path: dist/c/windows

    - name: Unzip C Bindings from macOS
      run: |
        unzip -o dist/c/macos/c-bindings-macos-latest.zip -d dist/c/macos
        rm dist/c/macos/c-bindings-macos-latest.zip

    - name: Unzip C Bindings from Ubuntu
      run: |
        unzip -o dist/c/linux/c-bindings-ubuntu-latest.zip -d dist/c/linux
        rm dist/c/linux/c-bindings-ubuntu-latest.zip
      
    # Skipping Windows for now
    # - name: Unzip C Bindings from Windows
    #   run: |
    #     unzip -o dist/c/windows/c-bindings-windows-latest.zip -d dist/c/windows
    #     rm dist/c/windows/c-bindings-windows-latest.zip

   ##### C++ Bindings #####

    - name: Download and Unzip C++ Bindings from All OSes
      # run: mkdir -p dist/c/macos dist/c/linux dist/c/windows
      run: mkdir -p dist/cpp/macos dist/c/linux

    - name: Download C++ Bindings from macOS
      uses: actions/download-artifact@v3
      with:
        name: cpp-bindings-macos-latest
        path: dist/cpp/macos

    - name: Download C++ Bindings from Ubuntu
      uses: actions/download-artifact@v3
      with:
        name: cpp-bindings-ubuntu-latest
        path: dist/cpp/linux

    # Skipping Windows for now
    # - name: Download C++ Bindings from Windows
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: cpp-bindings-windows-latest
    #     path: dist/cpp/windows

    - name: Unzip C++ Bindings from macOS
      run: |
        unzip -o dist/cpp/macos/cpp-bindings-macos-latest.zip -d dist/cpp/macos
        rm dist/cpp/macos/cpp-bindings-macos-latest.zip

    - name: Unzip C++ Bindings from Ubuntu
      run: |
        unzip -o dist/cpp/linux/cpp-bindings-ubuntu-latest.zip -d dist/cpp/linux
        rm dist/cpp/linux/cpp-bindings-ubuntu-latest.zip
      
    # Skipping Windows for now
    # - name: Unzip C++ Bindings from Windows
    #   run: |
    #     unzip -o dist/cpp/windows/cpp-bindings-windows-latest.zip -d dist/cpp/windows
    #     rm dist/cpp/windows/cpp-bindings-windows-latest.zip

   ##### Merge All Bindings #####

    - name: Zip All C Bindings Together
      run: zip -r compression-utils-c.zip dist/c

    - name: Zip All C++ Bindings Together
      run: zip -r compression-utils-cpp.zip dist/cpp

   ##### Upload Artifacts #####

    - name: Upload Unified C Bindings
      uses: actions/upload-artifact@v3
      with:
        name: compression-utils-c
        path: compression-utils-c.zip

    - name: Upload Unified C++ Bindings
      uses: actions/upload-artifact@v3
      with:
        name: compression-utils-cpp
        path: compression-utils-cpp.zip
