name: Build and Package Python Wheels

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Copy Python Bindings Configuration
        run: cp bindings/python/pyproject.toml . && cp bindings/python/setup.py .
  
      - name: Build Python Wheels
        env:
            CIBW_BUILD_VERBOSITY: 1
            CMAKE_BUILD_PARALLEL_LEVEL: 8
        run: cibuildwheel --output-dir wheelhouse
      
      - name: Upload Wheels as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
          retention-days: 5
